; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nanoatmega328]
platform = atmelavr
; board = nanoatmega328new        ;try on of them "board = nanoatmega328new" or "board = nanoatmega328"
board = nanoatmega328new   ;try on of them "board = nanoatmega328new" or "board = nanoatmega328"
framework = arduino
upload_port = /dev/ttyCH341USB2
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	adafruit/Adafruit Unified Sensor@^1.1.13
	nrf24/RF24@^1.4.7
	adafruit/MAX6675 library@^1.1.0
	adafruit/DHT sensor library@^1.4.6
board_build.mcu = atmega328p
board_build.f_cpu = 16000000L
